config/routes.rb
Rails.application.routes.draw do
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get    '/lookup', to: 'lookup#new'
  resources :genres
  resources :artists
  resources :adds
  resources :songs

  resources :users do
    resources :playlists, only: [:index]
  end
  resources :playlists, except: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/add.rb
class Add < ApplicationRecord

  belongs_to :playlist
  belongs_to :song

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs

end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :adds
  has_many :songs, through: :adds

  validates :name, presence: true  

  def add(song)
    self.songs << song 
  end
end

app/models/song.rb
class Song < ApplicationRecord
  has_many :adds
  has_many :playlists, through: :adds

  belongs_to :artist
  belongs_to :genre 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :playlists
  has_many :adds, through: :playlists

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }
  validates :username, presence: true, length: { minimum: 5 }, uniqueness: true

  def show_playlist

    if self.playlists.count < 1
      puts "You dont have any playlists"
    else
      self.playlists.each do |playlist|
        puts playlist
      end
    end

  end

end

app/controllers/adds_controller.rb
class AddsController < ApplicationController
  def new
    @add = Add.new
  end

  def create
    @add = Add.new(add_params)
    if @add.valid?
      @add.save
      redirect_to controller: 'playlists', action: 'show', id: @add.playlist_id
    else
      render :new
    end
  end

  private

  def add_params
    params.require(:add).permit(:playlist_id, :song_id)
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genres.all
  end

  def show
   @genre = Genre.find(params[:id])
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def index

    @user = User.find(params[:user_id])
    @playlists = @user.playlists
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
    # byebug
    @songs = Song.all
  end

  def create
    byebug
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = session[:user_id]
    if @playlist.valid?
      @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else 
      render 'new'
    end
  end

  def destroy 
    log_out 
    redirect_to controller: 'users', action: 'new'
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
    @add = Add.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    authorized(@user)
    @playlists = Playlist.find_by(params[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.update(params[:id])
    @user.update(user_params)
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lookup_helper.rb
module LookupHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !curret_user.nil?
  end

  def log_out 
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adds/new.erb
<%= form_for @add do |f| %>
<%= f.collection_select :playlist_id, Playlist.all, :id, :name %>
<%= f.collection_select :song_id, Song.all, :id, :title %>
<%= f.submit %>
<% end %>

app/views/artists/index.erb
<h1>List of Artists</h1>
<% @artists.each do |artist| %>
<div> <img style="max-width: 100px;" src="<%=artist.image%>" alt="artist image">  <%= link_to artist.name, artist  %> </div>
<br>
<%end%>

app/views/artists/show.erb
<h1><%=@artist.name%></h1>
<img style="width: 50%;" src="<%=@artist.image%>" alt="artits image">
<h3><%=@artist.blurbs%></h3>

app/views/playlists/index.erb
<% @playlists.each do |playlist| %>
<%= link_to playlist.name, user_playlists_path  %>
<% end %>

app/views/playlists/new.erb
<div style="width: 60%; margin: auto" class="jumbotron jumbotron-fluid">
<h1 style="text-align: center;">Create New Playlist</h1>
  <%= form_for @playlist  do |f|  %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %><br>
  


  <br>
  <br>
  <%= f.submit "Create Playlist", :class => 'btn btn-primary'  %>
  <% end %>
</div>

app/views/playlists/show.erb
<%= link_to "Create a New Playlist" %>
<h1><%= @playlist.name %></h1>
  <% @playlist.songs.each do |song|%>
  <%= song.title %>
<% end %>

app/views/songs/index.erb
Every Song
<% @songs.each do |song| %>
<h1><%= link_to song.artist.name, artist_path(song.artist.id) %> - <%=song.title %></h1>
<% end %>
<%= form_for @add do |f| %>
<%= f.collection_select :song_id, @songs, :id, :title %> 
<%= f.submit %>
<% end %>

app/views/users/edit.erb
<h1 style="text-align: center;">Edit User</h1>
<div style="width: 60%; margin: auto" class="jumbotron jumbotron-fluid">
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<br>
<%= f.submit "Update User", class: "btn btn-primary"  %>
<% end %>
</div>

app/views/users/new.html.erb
<div style="width: 60%; margin: auto" class="jumbotron jumbotron-fluid">
<h1 style="text-align: center">Create A New User</h1>
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Create Account" %>
<% end %>

</div>

app/views/users/show.erb
<style>
a {margin-left: 35%;
font-size: 30px
}

</style>

<h1><%= @user.name %></h1>

<h1 style="text-align: center">What would you like to do?</h1>
<div style="width: 60%; margin: auto" class="jumbotron jumbotron-fluid">
 <%= link_to " Create a Playlist", new_playlist_path, class: "fa fa-list"  %>  <br>
<%= link_to " View Playlists", @playlists, class: "fa fa-eye" %><br>
<%= link_to " Add Songs to Playlists", nil, class: "fa fa-plus" %><br>
<%= link_to " Edit Profile", edit_user_path, class: "fa fa-pencil"%><br>
<%= link_to " Search Artists", artists_path, class: "fa fa-music"  %><br>

<%= link_to "Delete Profile", nil, class: "fa fa-trash" %>
</div>